name: Build and deploy .NET Core app to Windows WebApp BlazorApp4Server20211210111935
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: BlazorApp4Server20211210111935
  AZURE_WEBAPP_PACKAGE_PATH: BlazorApp3\Server/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.BlazorApp4Server20211210111935_64a5 }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: BlazorApp3\Server
jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
        name: prod
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    #- name: Deploy to Azure WebApp
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    #    publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
